"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class actuators_t(object):
    __slots__ = ["de", "da", "dr", "dt"]

    def __init__(self):
        self.de = 0.0
        self.da = 0.0
        self.dr = 0.0
        self.dt = [ 0.0 for dim0 in range(8) ]

    def encode(self):
        buf = BytesIO()
        buf.write(actuators_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.de, self.da, self.dr))
        buf.write(struct.pack('>8d', *self.dt[:8]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != actuators_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return actuators_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = actuators_t()
        self.de, self.da, self.dr = struct.unpack(">ddd", buf.read(24))
        self.dt = struct.unpack('>8d', buf.read(64))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if actuators_t in parents: return 0
        tmphash = (0x1ab7f936254d9d65) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if actuators_t._packed_fingerprint is None:
            actuators_t._packed_fingerprint = struct.pack(">Q", actuators_t._get_hash_recursive([]))
        return actuators_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

