"""ZCM type definitions
This file automatically generated by zcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class sensor_baro_t(object):
    __slots__ = ["pressure", "temperature", "t"]

    def __init__(self):
        self.pressure = 0.0
        self.temperature = 0.0
        self.t = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(sensor_baro_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ddd", self.pressure, self.temperature, self.t))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sensor_baro_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sensor_baro_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sensor_baro_t()
        self.pressure, self.temperature, self.t = struct.unpack(">ddd", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sensor_baro_t in parents: return 0
        tmphash = (0x24df098c2a584c1a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + ((tmphash>>63)&0x1)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sensor_baro_t._packed_fingerprint is None:
            sensor_baro_t._packed_fingerprint = struct.pack(">Q", sensor_baro_t._get_hash_recursive([]))
        return sensor_baro_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

