// THIS IS AN AUTOMATICALLY GENERATED FILE.
// DO NOT MODIFY BY HAND!!
//
// Generated by zcm-gen

#include <string.h>
#ifndef ZCM_EMBEDDED
#include <stdio.h>
#endif
#include "sensor_data_t.h"

static int __sensor_data_t_hash_computed = 0;
static uint64_t __sensor_data_t_hash;

uint64_t __sensor_data_t_hash_recursive(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __sensor_data_t_get_hash)
            return 0;

    __zcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__sensor_data_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x794879f655918b74LL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __sensor_data_t_get_hash(void)
{
    if (!__sensor_data_t_hash_computed) {
        __sensor_data_t_hash = (int64_t)__sensor_data_t_hash_recursive(NULL);
        __sensor_data_t_hash_computed = 1;
    }

    return __sensor_data_t_hash;
}

int __sensor_data_t_encode_array(void* buf, uint32_t offset, uint32_t maxlen, const sensor_data_t* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].u), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].v), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].w), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].a_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].a_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].a_z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].p), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].q), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].r), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].phi), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].theta), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].psi), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].Vmag), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].alpha), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].beta), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].lat), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].lon), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].alt), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].t_sent), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int sensor_data_t_encode(void* buf, uint32_t offset, uint32_t maxlen, const sensor_data_t* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __sensor_data_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __sensor_data_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t __sensor_data_t_encoded_array_size(const sensor_data_t* p, uint32_t elements)
{
    uint32_t size = 0, element;
    for (element = 0; element < elements; ++element) {

        size += __double_encoded_array_size(&(p[element].x), 1);

        size += __double_encoded_array_size(&(p[element].y), 1);

        size += __double_encoded_array_size(&(p[element].z), 1);

        size += __double_encoded_array_size(&(p[element].u), 1);

        size += __double_encoded_array_size(&(p[element].v), 1);

        size += __double_encoded_array_size(&(p[element].w), 1);

        size += __double_encoded_array_size(&(p[element].a_x), 1);

        size += __double_encoded_array_size(&(p[element].a_y), 1);

        size += __double_encoded_array_size(&(p[element].a_z), 1);

        size += __double_encoded_array_size(&(p[element].p), 1);

        size += __double_encoded_array_size(&(p[element].q), 1);

        size += __double_encoded_array_size(&(p[element].r), 1);

        size += __double_encoded_array_size(&(p[element].phi), 1);

        size += __double_encoded_array_size(&(p[element].theta), 1);

        size += __double_encoded_array_size(&(p[element].psi), 1);

        size += __double_encoded_array_size(&(p[element].Vmag), 1);

        size += __double_encoded_array_size(&(p[element].alpha), 1);

        size += __double_encoded_array_size(&(p[element].beta), 1);

        size += __double_encoded_array_size(&(p[element].lat), 1);

        size += __double_encoded_array_size(&(p[element].lon), 1);

        size += __double_encoded_array_size(&(p[element].alt), 1);

        size += __double_encoded_array_size(&(p[element].t_sent), 1);

    }
    return size;
}

uint32_t sensor_data_t_encoded_size(const sensor_data_t* p)
{
    return 8 + __sensor_data_t_encoded_array_size(p, 1);
}

int __sensor_data_t_decode_array(const void* buf, uint32_t offset, uint32_t maxlen, sensor_data_t* p, uint32_t elements)
{
    uint32_t pos = 0, element;
    int thislen;

    for (element = 0; element < elements; ++element) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].u), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].v), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].w), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].a_x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].a_y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].a_z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].p), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].q), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].r), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].phi), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].theta), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].psi), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].Vmag), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].alpha), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].beta), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].lat), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].lon), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].alt), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].t_sent), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __sensor_data_t_decode_array_cleanup(sensor_data_t* p, uint32_t elements)
{
    uint32_t element;
    for (element = 0; element < elements; ++element) {

        __double_decode_array_cleanup(&(p[element].x), 1);

        __double_decode_array_cleanup(&(p[element].y), 1);

        __double_decode_array_cleanup(&(p[element].z), 1);

        __double_decode_array_cleanup(&(p[element].u), 1);

        __double_decode_array_cleanup(&(p[element].v), 1);

        __double_decode_array_cleanup(&(p[element].w), 1);

        __double_decode_array_cleanup(&(p[element].a_x), 1);

        __double_decode_array_cleanup(&(p[element].a_y), 1);

        __double_decode_array_cleanup(&(p[element].a_z), 1);

        __double_decode_array_cleanup(&(p[element].p), 1);

        __double_decode_array_cleanup(&(p[element].q), 1);

        __double_decode_array_cleanup(&(p[element].r), 1);

        __double_decode_array_cleanup(&(p[element].phi), 1);

        __double_decode_array_cleanup(&(p[element].theta), 1);

        __double_decode_array_cleanup(&(p[element].psi), 1);

        __double_decode_array_cleanup(&(p[element].Vmag), 1);

        __double_decode_array_cleanup(&(p[element].alpha), 1);

        __double_decode_array_cleanup(&(p[element].beta), 1);

        __double_decode_array_cleanup(&(p[element].lat), 1);

        __double_decode_array_cleanup(&(p[element].lon), 1);

        __double_decode_array_cleanup(&(p[element].alt), 1);

        __double_decode_array_cleanup(&(p[element].t_sent), 1);

    }
    return 0;
}

int sensor_data_t_decode(const void* buf, uint32_t offset, uint32_t maxlen, sensor_data_t* p)
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = __sensor_data_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __sensor_data_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int sensor_data_t_decode_cleanup(sensor_data_t* p)
{
    return __sensor_data_t_decode_array_cleanup(p, 1);
}

uint32_t __sensor_data_t_clone_array(const sensor_data_t* p, sensor_data_t* q, uint32_t elements)
{
    uint32_t n = 0, element;
    for (element = 0; element < elements; ++element) {

        n += __double_clone_array(&(p[element].x), &(q[element].x), 1);

        n += __double_clone_array(&(p[element].y), &(q[element].y), 1);

        n += __double_clone_array(&(p[element].z), &(q[element].z), 1);

        n += __double_clone_array(&(p[element].u), &(q[element].u), 1);

        n += __double_clone_array(&(p[element].v), &(q[element].v), 1);

        n += __double_clone_array(&(p[element].w), &(q[element].w), 1);

        n += __double_clone_array(&(p[element].a_x), &(q[element].a_x), 1);

        n += __double_clone_array(&(p[element].a_y), &(q[element].a_y), 1);

        n += __double_clone_array(&(p[element].a_z), &(q[element].a_z), 1);

        n += __double_clone_array(&(p[element].p), &(q[element].p), 1);

        n += __double_clone_array(&(p[element].q), &(q[element].q), 1);

        n += __double_clone_array(&(p[element].r), &(q[element].r), 1);

        n += __double_clone_array(&(p[element].phi), &(q[element].phi), 1);

        n += __double_clone_array(&(p[element].theta), &(q[element].theta), 1);

        n += __double_clone_array(&(p[element].psi), &(q[element].psi), 1);

        n += __double_clone_array(&(p[element].Vmag), &(q[element].Vmag), 1);

        n += __double_clone_array(&(p[element].alpha), &(q[element].alpha), 1);

        n += __double_clone_array(&(p[element].beta), &(q[element].beta), 1);

        n += __double_clone_array(&(p[element].lat), &(q[element].lat), 1);

        n += __double_clone_array(&(p[element].lon), &(q[element].lon), 1);

        n += __double_clone_array(&(p[element].alt), &(q[element].alt), 1);

        n += __double_clone_array(&(p[element].t_sent), &(q[element].t_sent), 1);

    }
    return n;
}

sensor_data_t* sensor_data_t_copy(const sensor_data_t* p)
{
    sensor_data_t* q = (sensor_data_t*) malloc(sizeof(sensor_data_t));
    __sensor_data_t_clone_array(p, q, 1);
    return q;
}

void sensor_data_t_destroy(sensor_data_t* p)
{
    __sensor_data_t_decode_array_cleanup(p, 1);
    free(p);
}

int sensor_data_t_publish(zcm_t* zcm, const char* channel, const sensor_data_t* p)
{
      uint32_t max_data_size = sensor_data_t_encoded_size (p);
      uint8_t* buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = sensor_data_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = zcm_publish (zcm, channel, buf, (uint32_t)data_size);
      free (buf);
      return status;
}

struct _sensor_data_t_subscription_t {
    sensor_data_t_handler_t user_handler;
    void* userdata;
    zcm_sub_t* z_sub;
};
static
void sensor_data_t_handler_stub (const zcm_recv_buf_t* rbuf,
                            const char* channel, void* userdata)
{
    int status;
    sensor_data_t p;
    memset(&p, 0, sizeof(sensor_data_t));
    status = sensor_data_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr, "error %d decoding sensor_data_t!!!\n", status);
        #endif
        return;
    }

    sensor_data_t_subscription_t* h = (sensor_data_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    sensor_data_t_decode_cleanup (&p);
}

sensor_data_t_subscription_t* sensor_data_t_subscribe (zcm_t* zcm,
                    const char* channel,
                    sensor_data_t_handler_t f, void* userdata)
{
    sensor_data_t_subscription_t* n = (sensor_data_t_subscription_t*)
                       malloc(sizeof(sensor_data_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->z_sub = zcm_subscribe (zcm, channel,
                              sensor_data_t_handler_stub, n);
    if (n->z_sub == NULL) {
        #ifndef ZCM_EMBEDDED
        fprintf (stderr,"couldn't reg sensor_data_t ZCM handler!\n");
        #endif
        free (n);
        return NULL;
    }
    return n;
}

int sensor_data_t_unsubscribe(zcm_t* zcm, sensor_data_t_subscription_t* hid)
{
    int status = zcm_unsubscribe (zcm, hid->z_sub);
    if (0 != status) {
        #ifndef ZCM_EMBEDDED
        fprintf(stderr,
           "couldn't unsubscribe sensor_data_t_handler %p!\n", hid);
        #endif
        return -1;
    }
    free (hid);
    return 0;
}

